### ISSUE TITLE
get different cost if we reorder the row of the cost matrix

### ISSUE THREAD

**Issue by chencjGene** [src-d/lapjv#9]
I first used a 52*52 cost matrix and get a cost of 3977.677734. Then I reorder this cost matrix in an inverted order, which supposes to get the same cost. However, we got a cost of 3975.381348.

I can provide the data if necessary.

**Comment by vmarkovtsev** [comment]
Hi @chencjGene 

I believe that this is the way JV algorithm works, since this project is just a Python wrapper + lossless optimizations over the ancient code. So I cannot really help here much. There is the original paper about the algorithm which I can send to you if you want to dig yourself.

Closing this as WONTFIX.

**Comment by bkj** [comment]
From my (relatively limited) experience looking at this code, the reason may come down to how ties are handled.  I've noticed that you can get radically different runtimes if you add a rank-1 random matrix `np.random.choice(2 ** 16, (N, 1)) @ np.random.choice(2 ** 16, (1, N))` to break ties in your cost matrix (which happen a lot eg when the cost matrix has lots of zeros)
